var recent_info_list=[
["https://www.cnbeta.com/articles/tech/828699.htm","英伟达发布嵌入式电脑Jetson Nano：功耗仅5W - nVIDIA - cnBeta.COM","搭载了四核Cortex-A57处理器，GPU则是拥有128个NVIDIA CUDA核心的NVIDIA麦克斯韦架构显卡，内存'''4GB''' LPDDR4，存储则为16GB eMMC 5.1，支持4K 60Hz视频解码。 Jetson Nano售价99美元，约合人民币'''660元'''。","日常办公、家用或家庭服务器"],
//-
["","射雕英雄传中的主要地名",`<div style="column-count: 2;">
* 蒙古 447
* 江南 315
* 桃花岛 291
* 金国 180
* 临安 105
* 大金国 91
* 华山 78
* 西域 55
* 中原 52
* 中国 40
* 太湖 40
* 黄河 39
* 大海 30
* 太阳 28
* 山东 26
* 北京 26
* 山洞 25
* 西北 24
* 波斯 21
* 君山 19
* 西湖 18
* 天竺 18
</div>
`,'#jieba #Python'],
["http://hznews.hangzhou.com.cn/wghz/content/2019-06/03/content_7204344.htm","余杭的洞霄名宫，凡间琼馆今安在？ - 杭州网 - 杭州新闻中心"],
["http://sh.eastday.com/m/20190607/u1ai12571168_K36320.html","2019电影党课启动 将持续4个月逾30部影片亮相--上海频道-东方网"],
["https://songshuhui.net/archives/105533","上班族如何吃得健康？我的看法跟许多营养师不一样 | 科学松鼠会"],
["https://sspai.com/post/55115","《全面战争：三国》评测：一场回溯过去的历史交锋 - 少数派"],
["https://sspai.com/post/55136","苹果新系统增加的这些功能，让你又可以少装一批第三方 App - 少数派"],
["https://sspai.com/post/55152","可能是近几年最有诚意的 iPad 系统更新：iPadOS 上手体验 - 少数派"],
["https://vimjc.com/how-to-start-vim.html?hmsr=toutiao.io&utm_medium=toutiao.io","怎么启动Vim？14个Vim启动参数和启动方法详解 | vim教程网"],
["https://www.cnbeta.com/articles/tech/855839.htm","制造商透露华为开始削减其PC产品产量 并暂停相关研发项目 - Huawei 华为 - cnBeta.COM"],
["https://www.cnbeta.com/articles/tech/856137.htm","富士康：如有需要，有足够产能向苹果供应美国境内销售的iPhone - Foxconn 富士康 - cnBeta.COM"],
["https://www.cnbeta.com/articles/tech/856139.htm","菜鸟联手快递公司上线新版电子面单：面积缩小近一半 - 电子商务 - 支付 / 金融科技 - cnBeta.COM"],
["https://www.cnbeta.com/articles/tech/856167.htm","受实体清单影响 西部数据中断与华为战略合作 - 硬件 - Western Digital 西部数据 - cnBeta.COM"],
["https://www.ifanr.com/1222391","吉野家推出「罐头饭」，日本的应急食品越来越精致了 | 爱范儿"],
["https://www.solidot.org/story?sid=60939","Solidot | 育碧宣布《Watch Dogs: Legion》"],
["https://www.solidot.org/story?sid=60942#comment_292315","Solidot | 中国电视机市场面临寒冬"],
["https://www.solidot.org/story?sid=60944","Solidot | 日本东京电子将切断与被美国列入黑名单的中国公司的合作"],
["http://fortune.com/2019/06/12/us-troops-to-poland-trump/","Trump Says He Might Move 2,000 U.S. Troops to Poland | Fortune"],
["http://i.jandan.net/2019/06/12/organic-farming.html","如何让花瓶中的花活得更久"],
["https://36kr.com/p/5214870","这个国家中心城市的崛起，才刚刚开始_36氪"],
["https://health.hangzhou.com.cn/hot/content/2019-06/12/content_7207340.htm","其实血糖值并非越低越好 低血糖比高血糖更致命_杭州网健康频道"],
["https://linux.cn/article-10962-1.html","技术|screen 命令示例：管理多个终端会话"],
["https://m.thepaper.cn/newsDetail_forward_3659615","5月CPI同比上涨2.7%，鲜果价格同比上涨26.7%_财经上下游_澎湃新闻"],
["https://songshuhui.net/archives/105752","世卫组织说每天喝水不能超过3.7升？喝水中毒的关键是这个 | 科学松鼠会"],
["https://www.cnbc.com/2019/06/12/huawei-scraps-laptop-launch-because-of-us-blacklisting.html","Huawei scraps laptop launch because of US blacklisting"],
["https://www.cnblogs.com/1121518wo/p/11011574.html","迭代器、生成器、装饰器学习总结 - tuxiaoping - 博客园"],
["https://www.ifanr.com/1223122","大疆机甲大师 S1 评测：科教娱乐兼备，3499 元售价是惊喜 | 爱范儿"],
["https://www.ifanr.com/1223704","田七被拍卖，曾经的知名牙膏品牌是怎么没落的？ | 爱范儿"],
["https://www.infoq.cn/article/atOTIv21qO6CuP_iiOs7","Python工程师如果还不会Jupyter Notebook，可能就落伍了 | 极客时间"],
["https://www.mnn.com/your-home/organic-farming-gardening/stories/how-make-cut-flowers-last-longer","How to make cut flowers last longer | MNN - Mother Nature Network"],
["https://www.oschina.net/news/107381/firefox-67-vs-chrome-75-linux-performance","Firefox 和 Chrome 性能测试对比 - OSCHINA"],
["https://www.solidot.org/story?sid=60951","Solidot | 越南指责中国给本国产品打上越南制造的标签"],
["https://www.solidot.org/story?sid=60958","Solidot | 西部数据将中止与华为的战略合作"],
["https://www.solidot.org/story?sid=60961","Solidot | 新研究大幅缩小系外复杂生命的搜索范围"],
["https://www.usatoday.com/story/news/world/2019/06/10/vietnam-alleges-china-faking-made-vietnam-skirt-us-tariffs/1408023001/","Vietnam alleges China is faking 'Made in Vietnam' to skirt US tariffs"],
["http://hznews.hangzhou.com.cn/shehui/content/2019-06/13/content_7209135_0.htm","关门1个月食品腐烂恶臭扑鼻 谁来管管失控的“鲜生友请”？ - 杭州网 - 杭州新闻中心"],
["http://m.nautil.us/issue/73/play/wechat-is-watching","WeChat Is Watching - Issue 73: Play - Nautilus"],
["http://news.sciencenet.cn/htmlnews/2019/6/427418.shtm","北京交通大学原校长宁滨因交通事故不幸逝世—新闻—科学网"],
["http://www.cbcgdf.org/NewsShow/4854/8534.html","草地贪夜蛾（秋粘虫）5月中旬或将入侵长江和江淮流域- 中国生物多样性保护与绿色发展基金会"],
["http://www.leikeji.com/article/26858","颜值为王！米家电烤箱32L发布：有独立控温与热风循环 - 雷科技"],
["http://www.xinhuanet.com/science/2018-09/27/c_137494393.htm","危害巨大的秋粘虫-科普中国"],
["https://m.leiphone.com/news/201906/T0WX6B4poRGphkuy.html","Google 推出免费利器，让编程小白也能开发游戏 | 雷锋网"],
["https://m.nbd.com.cn/articles/2019-05-14/1331241.html","又一农业害虫入侵 一天啃光一片玉米地 中国13省市遭受虫害 | 每日经济新闻"],
["https://m.nbd.com.cn/articles/2019-05-16/1332464.html","幺蛾子概念股爆发! 粮食杀手入侵中国? 专家: 尚无登记农药可用 | 每日经济新闻"],
["https://m.thepaper.cn/newsDetail_forward_3678222","8岁男孩就语文课本发问：江河里水被蒸干，羿怎么蹚过大河？_教育家_澎湃新闻"],
["https://m.thepaper.cn/newsDetail_forward_3679452","小学生质疑《羿射九日》， 人教社：“蹚”字不当，将修改_教育家_澎湃新闻"],
["https://m.thepaper.cn/newsDetail_forward_3683253","阿曼湾疑似遭袭油轮目前安全，特朗普坚称是伊朗制造袭击_澎湃国际_澎湃新闻"],
["https://m.thepaper.cn/newsDetail_forward_3684886","在久事艺术空间，品味戴敦邦绘画艺术_文化课_澎湃新闻"],
["https://m.weibo.cn/status/HysQ9b6SQ?jumpfrom=weibocom","山猫科普 海南一上市公司晚间公告称投资生产非洲猪瘟疫苗，引起我极大的兴趣。我仔细看下相关的介绍，其实要开发的不是疫苗，只是一种叫做今珠多糖的针剂。今珠多糖充其量就是一个多糖，虽然号称可以做一种免疫调节 - 白衣山猫 - 微博"],
["https://m.weibo.cn/status/HyteirxRq?jumpfrom=weibocom","山猫科普 自从我国发现非洲猪瘟以来，由于没有任何有效的治疗药物，农业农村部禁止治疗非洲猪瘟病猪。一个养猪场发现一头病猪，就必须将猪场内猪全部扑杀做无害化处理。 目前中国可以合法研究治疗非洲猪瘟的单位有 - 白衣山猫 - 微博"],
["https://www.asahichinese-j.com/photo/21610896","香港爆发大规模反条例修正案游行 部分队伍与警察发生冲突：朝日新聞中文网"],
["https://www.ifanr.com/app/1215466","专访钟颖：小白也能用的自动化神器，背后有什么秘密？ | 爱范儿"],
["https://www.oschina.net/news/107432/deluge-2-0-released","时隔两年，BT 下载客户端 Deluge 发布 2.0 版本 - OSCHINA"],
["https://www.solidot.org/story?sid=60963","Solidot | 埃博拉疫情从刚果扩散到乌干达"],
["https://www.solidot.org/story?sid=60968","Solidot | 华为要求 Verizon 支付 10 亿美元专利费"],
["https://www.solidot.org/story?sid=60982","Solidot | 香港警方逮捕 Telegram 群主"],
["https://www.solidot.org/story?sid=60991","Solidot | 用 Game Builder 创造自己的游戏"],
["https://www.solidot.org/story?sid=60993","Solidot | 中国探索用臭虫对抗秋行军虫"],
["http://hznews.hangzhou.com.cn/shehui/content/2019-06/14/content_7210422_0.htm","杭州地铁1号线紧急制停原因查明！原来是有人晕倒！地铁：不再追究 但下次真的别这么干了！ - 杭州网 - 杭州新闻中心"],
["https://m.thepaper.cn/newsDetail_forward_3688968","1岁幼童生日当天被生父从六楼扔下后死亡_直击现场_澎湃新闻"],
["https://m.weibo.cn/status/HyQQfxpDB?jumpfrom=weibocom","【海口高温今起得到缓解】 - 中国气象爱好者 - 微博"],
["https://segmentfault.com/a/1190000019474390","实用Javascript调试技巧分享 - 半路出家老菜鸟 - SegmentFault 思否"],
["https://sspai.com/post/55200","用了这个小工具，我把碎片知识都收集到了印象笔记 - 少数派"],
["https://sspai.com/post/55219","5 分钟，零基础也能轻松给视频加字幕 - 少数派"],
["https://www.boredpanda.com/why-cats-eat-bread-explained/","Tumblr User Explain Why Cats Are Obsessed With Eating Bread | Bored Panda"],
["https://www.cnbeta.com/articles/tech/857281.htm","中国半导体在5-10年内不可能自给自足 本土国产率只有4.2% - 硬件 - cnBeta.COM"],
["https://www.sciencemag.org/news/2019/06/psychologist-explains-why-people-confess-crimes-they-didn-t-commit","This psychologist explains why people confess to crimes they didn’t commit | Science | AAAS"],
["http://news.mtime.com/2019/06/14/1593931.html","《闪灵》续集《睡眠医生》首曝中字预告 导演接受时光网专访聊创作动机和拍摄过程 – Mtime时光网"],
["http://news.mtime.com/2019/06/15/1593969-all.html#p2","这部动漫神作，成就富坚义博 《幽游白书》连载25周年 回顾灵界大冒险 – Mtime时光网"],
["http://news.mtime.com/2019/06/15/1593971.html","2019中国电影票房收入同比减少16亿 观众不爱看电影了？8年来市场增速首度为负 – Mtime时光网"],
["https://m.thepaper.cn/newsDetail_forward_3428785","口述史︱一位历史地理学者眼中的三线企业_私家历史_澎湃新闻"],
["https://m.thepaper.cn/newsDetail_forward_3667403","评展｜乏味肤浅、缺乏思考的英国皇家艺术研究院夏季展_艺术评论_澎湃新闻"],
["https://m.thepaper.cn/newsDetail_forward_3687530","上海电影节丨《海上花》：一部“海上奇书”的百年跌宕_有戏_澎湃新闻"],
["https://m.thepaper.cn/newsDetail_forward_3687639","媒体披露江西永丰药膏激素之谜：销往全国，当地却很少用_绿政公署_澎湃新闻"],
["https://m.weibo.cn/status/HyYYC02Cd?jumpfrom=weibocom","【中国电影票房9年来首现负增长】 - 月光博客 - 微博"],
["https://photogrist.com/new-york-jeff-silberman/","Incredible Street Photography in New York by Jeff Silberman"],
["https://www.ifanr.com/1224382","买半价商务舱吗？禁飞罚款的那种 | 爱范儿"],
["http://news.sciencenet.cn/htmlnews/2019/6/427447.shtm","澳研究认为不健康饮食可引发脑功能退化—新闻—科学网"],
["https://betanews.com/2019/06/13/cern-malt-microsoft-alternative/","CERN is moving away from expensive Microsoft software and embracing open source | BetaNews"],
["https://betanews.com/2019/06/14/chrome-76-beta-bypass-paywall/","Chrome 76 makes it easier to get around paywalls | BetaNews"],
["https://linux.cn/article-10978-1.html","技术|如何使用 GParted 实用工具缩放根分区"],
["https://m.weibo.cn/status/Hz1oJq9Hh?jumpfrom=weibocom","【9图看懂水果含“糖”真相】 - 杭州发布 - 微博"],
["https://mp.weixin.qq.com/s/Meb-XCHj0Yj73KyMxw2Pyw","24式加速你的Python - Python与算法之美"],
["https://mp.weixin.qq.com/s/QOGHeki-NiWZ6NryQyqV3Q","客运收入无法覆盖成本，各城地铁公司都是如何赚钱的？ - 杭州地铁2012","","高铁、地铁和毛时代的大锅饭没多少区别"],
["https://www.cnbeta.com/articles/tech/857639.htm","百度网盘Linux版正式发布：专为中标麒麟桌面操作系统打造 - Baidu 百度 - cnBeta.COM"],
["https://www.itcodemonkey.com/article/15081.html","从0开始学正则，让正则成为你的解析利器 - IT程序猿"],
["https://www.itcodemonkey.com/article/15090.html","黑客最想要的礼物！看完我也眼红了 - IT程序猿"],
["https://www.itcodemonkey.com/article/15106.html","CSS3中Flex弹性布局该如何灵活运用？ - IT程序猿"],
["https://www.lowyinstitute.org/the-interpreter/why-china-s-rulers-won-t-admit-they-could-be-wrong","Why China’s rulers won’t admit they could be wrong | The Interpreter"],
["https://www.newsmarket.com.tw/blog/121223/","秋行軍蟲0613》殺蟲教戰手冊！外貌糞便咬痕揪蟲，專家：秋行軍蟲易有抗藥性「看到蟲才用藥」 | 上下游News&Market"],
["https://www.newsmarket.com.tw/blog/121271/","秋行軍蟲0614》全台淪陷，幼蟲出沒如天女散花！馬祖澎湖捕獲成蟲拉警報 | 上下游News&Market"],
["https://www.newsmarket.com.tw/blog/121299/","（獨家）秋行軍蟲如何從中國飛來？日本高度警戒，恐已入侵沖繩、九州 | 上下游News&Market"],
["https://www.v2ex.com/t/574185?p=1","百度网盘居然出 Linux 版了 - V2EX"],
["http://blog.sciencenet.cn/blog-279293-1185547.html","科学网—自然哲学与自然科学对“抽象思维”的不同需求——兼与农绍庄教授商榷 - 聂广的博文"],
["http://i.jandan.net/2019/06/16/bubble-tea-abdomen.html","少女腹内堆积超100颗奶茶“珍珠”"],
["http://i.jandan.net/2019/06/16/survives-four-days.html","老人与海：四天三夜的海上漂流记"],
["http://i.jandan.net/2019/06/17/universal-beauty.html","所有山脉在数学上都具有普遍的优美特征"],
["http://iot.51cto.com/art/201906/597959.htm","当监狱遇到物联网，肖申克还能完成他的“救赎”吗？ - 51CTO.COM"],
["http://news.mtime.com/2019/06/16/1594004-all.html#p3","日本人到底有多爱“三国”？！ 《赤壁》比中国更卖座 游戏层出不穷 – Mtime时光网"],
["http://news.mtime.com/2019/06/17/1594052.html","奥斯卡最佳纪录片《徒手攀岩》引进内地 攀岩大师4小时徒手攀登3000英尺高酋长岩 – Mtime时光网"],
["http://www.womanhospital.cn/xwzx/news_fyxw_detail.aspx?id=4577&cid=1726","人乳捐赠其实和献血一样重要"],
["https://36kr.com/p/5216481?ktm_source=feed","最前线 | 格兰仕称在天猫遭搜索异常，第一家站拼多多怼阿里的品牌商出现了_36氪"],
["https://facebook.github.io/react-native/","React Native · A framework for building native apps using React"],
["https://m.leiphone.com/news/201906/3kV3qiFwdjy0nbd4.html","实录 | 任正非对话两位美国思想家：华为是打不死的鸟 | 雷锋网"],
["https://m.thepaper.cn/newsDetail_forward_3680198","城市与社会︱跑步APP使用者：在解放与控制之间_澎湃研究所_澎湃新闻"],
["https://m.thepaper.cn/newsDetail_forward_3693904","深圳被小区坠窗砸伤男童离世，7.5万治疗费物业代交了三千_直击现场_澎湃新闻"],
["https://m.thepaper.cn/newsDetail_forward_3693926","31省份常住人口排行榜出炉：广东仍第一，27省份呈正增长_中国政库_澎湃新闻"],
["https://m.thepaper.cn/newsDetail_forward_3694044?hotComm=true","台湾超市女员工偷吃两颗茶叶蛋被判3个月，法院：是最轻判罚_港台来信_澎湃新闻"],
["https://m.thepaper.cn/newsDetail_forward_3696097","成都宜宾高铁投运，“川南龙头”城市之争再添变数_媒体_澎湃新闻-The Paper"],
["https://m.thepaper.cn/newsDetail_forward_3697211","应急管理部：本轮暴雨洪涝灾害已造成88人死亡、17人失踪_绿政公署_澎湃新闻"],
["https://mp.weixin.qq.com/s/dQDX-kk88gbqql38M2RwmA","给 node.js 白嫖怪的5个免费托管服务 - 码农英语课堂"],
["https://mp.weixin.qq.com/s?__biz=MzAwMzQyMDAxNA==&mid=2655278148&idx=1&sn=0120e498085d44be575a1e3bc2573273&chksm=808b8e45b7fc07532a204589c38fcf19893b8bcbf8a6f075983baa3416ff5f7c49fedb985515&mpshare=1&scene=1&srcid=&key=865d3b2aee7ad3a931811c48a4b77448967dbb53722c363232b972bcd7e49ae7d3e53a56f07a1dc65928a2849c998681a1ac2962da87908397877d0c54c6099d0c51fdc1f5dcc8ac63d502a98bf02a54&ascene=1&uin=NDIxMjQ2MTM1&devicetype=Windows+10&version=62060834&lang=zh_CN&pass_ticket=3%2FaTbMe0r%2BPyCA%2BGoGj7HznJ2jB3PRokPfv0FxfB%2BmubO%2FC5Jak4OqMbhkjbCZTR","关于格兰仕在天猫平台出现搜索异常的声明 - 格兰仕服务"],
["https://post.m.smzdm.com/p/aqnddoqp/","笔记本光驱位加装固态硬盘手把手教程，简单无拆机，几个步骤让旧机焕发活力_值客原创_什么值得买"],
["https://segmentfault.com/a/1190000019485560","使用Node.js爬取任意网页资源并输出高质量PDF文件到本地~ - 跨平台全栈俱乐部 - SegmentFault 思否"],
["https://songshuhui.net/archives/105756","喝绿茶导致急性肝炎？真相是这样的 | 科学松鼠会"],
["https://soranews24.com/2019/06/15/japanese-beef-bowl-chain-yoshinoya-releases-new-canned-ready-to-eat-rice-bowls-%e3%80%90taste-test%e3%80%91/","Japanese beef bowl chain Yoshinoya releases new canned, ready-to-eat rice bowls 【Taste Test】 | SoraNews24 -Japan News-"],
["https://www.chiphell.com/thread-2006869-1-1.html?mobile=2","我们的世界~重庆~3-5月摄影记录（图多） - 摄影作品 - Chiphell - 分享与交流用户体验 - 手机版 - Powered by Discuz!"],
["https://www.cnbeta.com/articles/tech/857743.htm","爱否科技创始人彭林宣布辞职 起诉知名厂商“拍月亮造假”行为 - 最新消息 - cnBeta.COM"],
["https://www.douban.com/event/32336826/","敝帚自珍：丰子恺漫画特展_豆瓣"],
["https://www.itcodemonkey.com/article/15074.html","用故事的形式趣说Python单例模式 - IT程序猿"],
["https://www.itcodemonkey.com/article/15097.html","什么是自签名数字证书？ - IT程序猿"],
["https://www.itcodemonkey.com/article/15114.html","如何分析一条SQL的性能 - IT程序猿"],
["https://www.livescience.com/65705-bubble-tea-abdomen-constipation.html","An X-Ray Showing 100 Bubble Tea Pearls in a Teen's Abdomen Has Doctors Very Confused"],
["https://www.odditycentral.com/news/60-year-old-man-survives-four-days-stranded-at-sea-with-no-food-or-water.html","60-Year-Old Man Survives Four Days Stranded at Sea with No Food or Water"],
["https://www.sciencealert.com/there-s-a-universal-beauty-in-the-structure-of-earth-s-mountains","There's a Strange, Universal Beauty in The Structure of Earth's Mountains"],
["https://www.sysgeek.cn/windows-10-english-language-different/","同样是 Windows 10 英文版，概要「英语」和「英语（国际）」之差异"],
["https://www.v2ex.com/t/574549#reply10","新手请教关于 Python 函数参数默认值设计的问题 - V2EX"],

];
